version: '3.4'

networks:
  todo.network:

services:
  todo.api:
    image: ${DOCKER_REGISTRY-}todoapi
    build:
      context: .
      dockerfile: ToDo.Api/Dockerfile
    networks:
      - todo.network
  todo.client:
    build:
      context: ./ToDo.Client
      dockerfile: Dockerfile
    ports:
      - "3100:80"
    depends_on:
      - todo.api